// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDewv-TF8Q3Eazn11ntANso3r72pLlk8ek',
    appId: '1:544156502073:web:b95c4b133af824301f25e8',
    messagingSenderId: '544156502073',
    projectId: 'kanbanboard-by-mary',
    authDomain: 'kanbanboard-by-mary.firebaseapp.com',
    storageBucket: 'kanbanboard-by-mary.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqUz-Aw3C8iNc7IXOE6hN5Y2gMLLIjKzU',
    appId: '1:544156502073:android:fd067b8cf3af47521f25e8',
    messagingSenderId: '544156502073',
    projectId: 'kanbanboard-by-mary',
    storageBucket: 'kanbanboard-by-mary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSUxDmIKzdxwpAFxoQ_KHfzFkDtzUTozk',
    appId: '1:544156502073:ios:77d8820c15ee23aa1f25e8',
    messagingSenderId: '544156502073',
    projectId: 'kanbanboard-by-mary',
    storageBucket: 'kanbanboard-by-mary.firebasestorage.app',
    iosBundleId: 'com.buildwithmary.buildWithMary',
  );
}
